language: csharp
mono: latest
env: TARGET_LANG=csharp

matrix:
  include:
    - env: TARGET_LANG=java
      jdk: oraclejdk8

    - env: TARGET_LANG=ruby
      rvm: 2.0.0
    - env: TARGET_LANG=ruby
      rvm: 2.1.0
    - env: TARGET_LANG=ruby
      rvm: 2.2.0
    - env: TARGET_LANG=ruby
      rvm: jruby-head

    - env: TARGET_LANG=javascript
      node_js: 0.12

    - env: TARGET_LANG=golang
      go: 1.3
    - env: TARGET_LANG=golang
      go: 1.4
    - env: TARGET_LANG=golang
      go: tip

before_install:
  - export EnableNuGetPackageRestore=true
  # https://github.com/travis-ci/travis-ci/issues/2839
  - export JAVA_HOME="$(/usr/libexec/java_home)"
  # install jq
  - sudo apt-get install -y jq

script: "cd $TARGET_LANG; make"

branches:
  only:
    - master

notifications:
  email:
    - cukes-devs@googlegroups.com
  irc:
    - "irc.freenode.org#cucumber"
